### PR TITLE
Junior/Mid-level challenge

### PR DESCRIPTION
**Pull request by jtmclucas13**
**This is a Draft PR because we don't intend to merge this code to master. This is a vehicle for discussion, and changes can be PR'd against the `intro-challenge` branch or merged directly in.**

# Situation

We expect all Retrium engineers to be sufficiently proficient in JavaScript and React in order to hire them. We expect all prospective Retrimaniacs to understand the basics of unit testing and algorithmic problem solving in order to hire them. We evaluate all engineers, regardless of experience level, with the same take-home and mob coding challenge.

# Complication

We want to include junior and mid-level engineers in our hiring process. It is both unfair and unrealistic to provide the same challenge to people at all stages of their career. We want our process to remain efficient, being able to re-use as much of it as possible. We should understand how to evaluate performance on the project.

# Questions

- How much help should we provide non-seniors with the Game Of Life algorithm and data structure?

- How much help should we provide non-seniors with unit testing?

- What unit testing frameworks should we provide?

- Is the project briefing clear?

- Does the project repo function as expected?

# Answers
(Seeking feedback on every Question! Feel free to answer with PR comments, changes, or approvals.)

- How much help should we provide non-seniors with the Game Of Life algorithm and data structure?

This branch now includes a skeleton function that does nothing and a couple example boards used in unit tests. I think this might be sufficient for mid-level folks, but I'm not sure about juniors. I considered adding a comment to explain the data structure (this might be necessary for everyone) or filling out the `getNextGeneration` function a bit. What do we think?

- How much help should we provide non-seniors with unit testing?

I provided a test of a still life (which passes out of the box) and an oscillator (which fails out of the box). I would hope candidates would add at least one more board test in addition to testing whatever helper functions they write for the game. Is it too much? Should we just provide the names of a few tests and not the implementations? Should we just provide the still life test?

- What unit testing frameworks should we provide?

I provided a plain JS example, Mocha, Jest, and Tape. I've never used Mocha, so I'm not sure that the setup is standard - I don't know if that's more harm than hurt. For example, Chai is typically used with Mocha, but I didn't install it. Is it too much/overwhelming, or is it helpful? I imagine we'd either provide a bunch of options or a single option, so they don't have to choose.

- Is the project briefing clear?

You tell me! I did some tweaking of the README

- Does the project repo function as expected?

Does it?

### CODE REVIEW

**Review by xylude — COMMENTED** [review]
I can't tell whether we should document more on the meaning of the shape of the board state. It seems obvious to me looking at it and probably is fine but maybe we should have a short description to give clarity to it.

**Comment by sarahsundgren** [comment]
> How much help should we provide non-seniors with the Game Of Life algorithm and data structure?

I like the two example board for being one that doesn't change, and one that changes back and forth. It'll be interesting to see what other boards folks decide to test with (if any).

I think I would add a comment that lets candidates know they could do something different if they like. "These example boards denote the row and column of live cells with an empty array being an empty row. Feel free to keep this data structure or change it to what works best for you".

I don't think the `getNextGeneration` function needs anything else.

**Comment by sarahsundgren** [comment]
>How much help should we provide non-seniors with unit testing?

I'm tempted to say we should just provide the still life test; then they can pretty easily add the blinker test plus others. But that feels almost the same as us providing both tests.

**Comment by sarahsundgren** [comment]
>What unit testing frameworks should we provide?

Supplying 4 different test frameworks seems helpful to me; one of those they are probably familiar with and can jump right into it.

**Comment by sarahsundgren** [comment]
>Is the project briefing clear?

>Does the project repo function as expected?

Yes and yes

**Comment by jtmclucas13** [comment]
I integrated both of y'alls suggestions - I think we're good to give this to someone soon!

**Pull request closed without merging**
